package push.tester.utils;

enum ErrorCode {
	OK, INVALID_SCHEMA_FORMAT, UNEXPECTED_ARGUMENT,
	INVALID_SCHEMA_NAME,
	MISSING_STRING,
	MISSING_INTEGER, INVALID_INTEGER,
	MISSING_DOUBLE, INVALID_DOUBLE
}
